"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Circle_1 = require("./Circle");
var Shape_1 = require("./Shape");
var Rectangle_1 = require("./Rectangle");
var myShape = new Shape_1.Shape(10, 15);
console.log(myShape.getInfo());
var myCircle = new Circle_1.Circle(5, 10, 200);
console.log(myCircle.getInfo());
var myRect = new Rectangle_1.Rectangle(0, 2, 4, 6);
console.log(myRect.getInfo());
